<?php
/**
 * Created by PhpStorm.
 * User: Ivan
 * Date: 20/03/2018
 * Time: 7:40 AM
 */

namespace IvanCLi\Tests\Components;


use Orchestra\Testbench\TestCase;

class StockBuilderTest extends TestCase
{
    protected function getPackageProviders($app)
    {
        return ['IvanCLi\AlphaVantage\AlphaVantageServiceProvider'];
    }

    protected function getPackageAliases($app)
    {
        return ['AlphaVantage' => '\IvanCLi\AlphaVantage\Facades\AlphaVantage'];
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testNullAPIKey()
    {
        try {
            \AlphaVantage::stock();
            $this->assertFalse(true,
                'Alpha Vantage Service Constructor didn\'t throw exception even when API Key is not provided.');
        } catch (\Exception $e) {
            $this->assertTrue(true);
        }
    }

    public function testIntradaySuccessQuery()
    {
        print_r(\AlphaVantage::stock());
        exit();

        $this->assertTrue(true);
    }
}